apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spring-academy-guides-upgrade-boot-2x-to-3x-in-practice
spec:
  title: "Upgrading Spring Boot from 2.x to 3.x in Practice"
  description: "Upgrading Spring Boot from 2.x to 3.x in Practice"
  workshop:
    image: jdk17-environment:*
    files:
      - http:
          # the name of the tar.gz here should make the workshop name
          url: "$(ingress_protocol)://$(workshop_namespace)-files.$(ingress_domain)/spring-academy-guides-upgrade-boot-2x-to-3x-in-practice.tar.gz"
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/spring-academy/course-spring-boot-2-7-to-3-1-upgrade-code
          ref: with-hints
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    env:
      - name: LESSON_LABEL
        value: with-hints
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
    volumes:
    - name: workshop-init-container-scripts
      secret:
        secretName: workshop-init-container-scripts
        defaultMode: 0755
    patches:
      initContainers:
      - name: pre-session-setup
        # Educates needs a $(base_environment_image) variable can use.
        # For now hard wire to educates-base-environment image. Aim to
        # change for Educates 2.6.0.
        image: ghcr.io/educates/educates-base-environment:3.3.3
        # Execute setup script mounted from secret.
        command: ["/opt/init-setup-scripts/setup.sh"]
        volumeMounts:
        - name: workshop-init-container-scripts
  environment:
    objects:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: workshop-init-container-scripts
      stringData:
        setup.sh: |
          #!/bin/bash
          set -x
          set -eo pipefail
          echo "Put commands here that need to be done in init container prior to workshop session"
    - apiVersion: v1
      kind: Service
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        type: ClusterIP
        ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
        selector:
          deployment: files
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        tls:
        - hosts:
            - $(workshop_namespace)-files.$(ingress_domain)
          secretName: $(ingress_secret)
        rules:
        - host: $(workshop_namespace)-files.$(ingress_domain)
          http:
            paths:
            - backend:
                service:
                  name: $(workshop_namespace)-files
                  port:
                    number: 80
              pathType: Prefix
              path: /
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        serviceAccountName: $(service_account)
        replicas: 1
        selector:
          matchLabels:
            deployment: files
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deployment: files
          spec:
            containers:
            - name: files
              image: ghcr.io/spring-academy/spring-guides:${VERSION}