apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spring-academy-guides-upgrade-boot-2x-to-3x-in-practice
spec:
  title: "Upgrading Spring Boot from 2.x to 3.x in Practice"
  description: "Upgrading Spring Boot from 2.x to 3.x in Practice"
  workshop:
    image: jdk17-environment:*
    files:
      - http:
          # the name of the tar.gz here should make the workshop name
          url: "$(ingress_protocol)://$(assets_repository)/spring-academy-guides-upgrade-boot-2x-to-3x-in-practice.tar.gz"
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/spring-academy/course-spring-boot-2-7-to-3-1-upgrade-code
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    env:
      - name: LESSON_LABEL
        value: with-hints
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
  environment:
    assets:
      memory: 0Mi
      ingress:
        enabled: true
      files:
        - image:
            url: ghcr.io/spring-academy/spring-guides:${VERSION}
          newRootPath: usr/share/nginx/html