apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-guides-spring-modulith-deep-dive
spec:
  title: "Spring Modulith Deep Dive"
  description: "Spring Modulith Deep Dive"
  workshop:
    image: jdk21-environment:*
    files:
      - http:
          # the name of the tar.gz here should make the workshop name
          url: "$(ingress_protocol)://$(assets_repository)/spr-guides-spring-modulith-deep-dive.tar.gz"
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/odrotbohm/spring-modulith-deep-dive
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
  environment:
    assets:
      memory: 0Mi
      ingress:
        enabled: true
      files:
        - image:
            url: ghcr.io/spring-academy/spring-guides:${VERSION}
          newRootPath: usr/share/nginx/html