apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-guides-spring-modulith-deep-dive
spec:
  title: "Spring Modulith Deep Dive"
  description: "Spring Modulith Deep Dive"
  workshop:
    image: jdk21-environment:*
    files:
      - image:
          url: $(image_repository)/spring-guides-files:$(workshop_version)
        includePaths:
          - /workshops/spring-modulith-deep-dive/workshop/**
        newRootPath: workshops/spring-modulith-deep-dive
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/odrotbohm/spring-modulith-deep-dive
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
