:spring_boot_version: 3.1.1
:spring-boot: https://github.com/spring-projects/spring-boot
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot

This guide provides a sampling of how https://spring.io/projects/spring-boot[Spring Boot] helps you accelerate
application development. As you read more Spring Getting Started guides, you will see more
use cases for Spring Boot. This guide is meant to give you a quick taste of Spring Boot.


== What You Will build

Starting from scratch, you will build a starter app with Spring Initializr, and from it create a simple Spring Boot web application which includes some useful services.

In order to create your own Spring Boot-based project, normally you would visit
https://start.spring.io/[Spring Initializr^], fill in your project details, pick your
options, and download a bundled up project as a zip file. In this lab,
we've provided Spring Initializer in the tab to the right.


== What You Need
* About 15 minutes

* A favorite text editor or IDE. We recommend one of the following:
** https://spring.io/guides/gs/intellij-idea/[IntelliJ IDEA]
** https://spring.io/guides/gs/guides-with-vscode/[Visual Studio Code]
* https://www.oracle.com/java/technologies/downloads/[Java 17 or later]
* https://gradle.org/install/[Gradle 7.5+]


