:spring_boot_version: 3.1.1
:spring-boot: https://github.com/spring-projects/spring-boot
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot

Congratulations! You built a simple web application with Spring Boot and learned how it
can ramp up your development pace. You also turned on some handy production services.
This is only a small sampling of what Spring Boot can do. 

See
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle[Spring Boot's reference documentation]
for much more information about the Spring Boot framework.

== See Also

The following courses offer a more extensive introduction to Spring Boot:

* An in-depth introduction: https://spring.academy/courses/building-a-rest-api-with-spring-boot[Building a REST API with Spring Boot]
* A deeper dive: https://spring.academy/courses/spring-boot[Spring Boot]

The following guides may also be helpful:

* https://spring.io/guides/gs/securing-web/[Securing a Web Application]
* https://spring.io/guides/gs/serving-web-content/[Serving Web Content with Spring MVC]

Want to write a new guide or contribute to an existing one? Check out our https://github.com/spring-guides/getting-started-guides/wiki[contribution guidelines].

IMPORTANT: All guides are released with an ASLv2 license for the code, and an http://creativecommons.org/licenses/by-nd/3.0/[Attribution, NoDerivatives creative commons license] for the writing.
