apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spring-academy-guides-upgrade-from-spring-boot-2x-to-3x
spec:
  title: "Closing the Gap: Upgrading your App from Spring Boot 2.x to 3.x"
  description: "Closing the Gap: Upgrading your App from Spring Boot 2.x to 3.x"
  workshop:
    image: jdk8-environment:*
    packages:
      - name: spring-academy-lab
        files:
          - image:
              url: ghcr.io/spring-academy/spring-academy-extension-packages/spring-academy-lab
              tagSelection:
                semver:
                  constraints: ">=1.0.0 <2.0.0"
    files:
      - image: # Note: format is {repository-name}-files
          url: $(image_repository)/spring-guides-files:$(workshop_version)
        includePaths:
          - /workshops/10-closing-the-gap-upgrade/workshop/**
        newRootPath: workshops/10-closing-the-gap-upgrade
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/spring-academy/course-spring-boot-2-5-upgrade-code
          ref: ilw
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    env:
      - name: LESSON_LABEL
        value: 01-ilw-start-01
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
